name: retail-backend-project

services:
  retail-app:
    container_name: retail-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - KAFKA_BOOTSTRAP_SERVER=${KAFKA_BOOTSTRAP_SERVER}
      - KAFKA_KEY=${KAFKA_KEY}
      - KAFKA_SECRET=${KAFKA_SECRET}
    restart: no
    networks:
      - retail-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  retail-network:
    driver: bridge